export const PRODUCT_ANALYSIS_REQUEST = "PRODUCT_ANALYSIS_REQUEST";
export const PRODUCT_ANALYSIS_SUCCESS = "PRODUCT_ANALYSIS_SUCCESS";
export const PRODUCT_ANALYSIS_FAIL = "PRODUCT_ANALYSIS_FAIL";
export const PRODUCT_ANALYSIS_RESET = "PRODUCT_ANALYSIS_RESET";

export const SELLER_ANALYSIS_REQUEST = "SELLER_ANALYSIS_REQUEST";
export const SELLER_ANALYSIS_SUCCESS = "SELLER_ANALYSIS_SUCCESS";
export const SELLER_ANALYSIS_FAIL = "SELLER_ANALYSIS_FAIL";
export const SELLER_ANALYSIS_RESET = "SELLER_ANALYSIS_RESET";

export const SELLER_MONTHLY_ANALYSIS_MONTHLY_REQUEST =
  "SELLER_MONTHLY_ANALYSIS_MONTHLY_REQUEST";
export const SELLER_MONTHLY_ANALYSIS_MONTHLY_SUCCESS =
  "SELLER_MONTHLY_ANALYSIS_MONTHLY_SUCCESS";
export const SELLER_MONTHLY_ANALYSIS_MONTHLY_FAIL =
  "SELLER_MONTHLY_ANALYSIS_MONTHLY_FAIL";
export const SELLER_MONTHLY_ANALYSIS_MONTHLY_RESET =
  "SELLER_MONTHLY_ANALYSIS_MONTHLY_RESET";
