export const PRODUCT_ANALYSIS_REQUEST = "PRODUCT_ANALYSIS_REQUEST";
export const PRODUCT_ANALYSIS_SUCCESS = "PRODUCT_ANALYSIS_SUCCESS";
export const PRODUCT_ANALYSIS_FAIL = "PRODUCT_ANALYSIS_FAIL";
export const PRODUCT_ANALYSIS_RESET = "PRODUCT_ANALYSIS_RESET";
