import bcrypt from "bcryptjs";
import mongoose from "mongoose";
// import { frigider } from "..";
const ObjectId = mongoose.Types.ObjectId;
const data = {
  users: [
    {
      _id: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Daniel",
      email: "danieleliyho@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Daniel Fitness",
        logo: "/seller1/fitnesslogo.png",
        description: "best seller",
        rating: 0,
        numReviews: 0,
      },
    },
    {
      _id: ObjectId("60e87e474f88c268a82a9ed3"),

      name: "Adi3",
      email: "adi@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: "Adi Appliances",
        logo: "/seller2/electriclogo.jpg",
        description: "best seller",
        rating: 0,
        numReviews: 0,
      },
    },
    {
      name: "Adi",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
    {
      name: "Adi1",
      email: "user3@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
    {
      name: "Adi2",
      email: "user2@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Adidas Brown Shirt",
      category: "Shirts",
      image: [
        "/seller1/adidasshirt1.jpg",
        "/seller1/adidasshirt2.jpg",
        "/seller1/adidasshirt3.jpg",
      ],
      price: 80,
      countInStock: 22,
      brand: "Adidas",
      rating: 0,
      numReviews: 0,
      description: "high quality adidas Shirt",
    },
    {
      name: "Adidas Red Shirt",
      seller: ObjectId("000004d2a9df6b66efb190ac"),

      category: "Shirts",
      image: [
        "/seller1/adidasshirt4.jpg",
        "/seller1/adidasshirt5.jpg",
        "/seller1/adidasshirt6.jpg",
      ],
      price: 66,
      countInStock: 12,
      brand: "Adidas",
      rating: 0,
      numReviews: 0,
      description: "high quality adidas Shirt",
    },
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Best protein powder",
      category: "protein powder",
      image: ["/seller1/best1.jpeg"],
      price: 110,
      countInStock: 72,
      brand: "best",
      rating: 0,
      numReviews: 0,
      description: "high quality protein powder",
    },
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Combat protein powder",
      category: "protein powder",
      image: ["/seller1/combat1.jpeg", "/seller1/combat2.jpeg"],
      price: 110,
      countInStock: 72,
      brand: "combat",
      rating: 0,
      numReviews: 0,
      description:
        "University-studies formulated: MusclePharm combat protein powder was created for athletes who demand optimized recovery, muscle growth, and support strength.",
    },
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Dymatize protein powder",
      category: "protein powder",
      image: ["/seller1/Dymatize1.png", "/seller1/Dymatize2.png"],
      price: 90,
      countInStock: 30,
      brand: "Dymatize",
      rating: 0,
      numReviews: 0,
      description: "best protein powder",
    },
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "OneWhey protein powder",
      category: "protein powder",
      image: ["/seller1/onewhey.jpeg"],
      price: 77,
      countInStock: 10,
      brand: "OneWhey",
      rating: 0,
      numReviews: 0,
      description: "OneWhey protein powder with a new formula",
    },
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Sejan bike",
      category: "bike",
      image: ["/seller1/bike5.jpeg", "/seller1/bike6.jpg"],
      price: 500,
      countInStock: 10,
      brand: "sejan",
      rating: 0,
      numReviews: 0,
      description: "best bike",
    },
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Iess bike",
      category: "bike",
      image: ["/seller1/bike1.png", "/seller1/bike2.png"],
      price: 600,
      countInStock: 10,
      brand: "Iess",
      rating: 0,
      numReviews: 0,
      description: "Start riding your bike at home",
    },
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Head bike 2jp",
      category: "bike",
      image: ["/seller1/bike7.jpg", "/seller1/bike8.jpg"],
      price: 600,
      countInStock: 10,
      brand: "Head",
      rating: 0,
      numReviews: 0,
      description: "Head best bike",
    },
    {
      seller: ObjectId("000004d2a9df6b66efb190ac"),
      name: "Head bike",
      category: "bike",
      image: ["/seller1/bike3.jpg", "/seller1/bike4.jpg"],
      price: 450,
      countInStock: 10,
      brand: "Head",
      rating: 0,
      numReviews: 0,
      description: "Head best bike",
    },
    {
      seller: ObjectId("60e87e474f88c268a82a9ed3"),
      name: "4K SMART LG OLED48C1",
      category: "TV",
      image: [
        "/seller2/lgoled1.png",
        "/seller2/lgoled2.jpg",
        "/seller2/lgoled3.jpg",
      ],
      price: 600,
      countInStock: 12,
      brand: "LG",
      rating: 0,
      numReviews: 0,
      description:
        "OLED technology monitor with 8.3 million pixels independently lit 9 α 4 ′ 4G 4K image processor for ultimate image and sound Captivating cinema and sports experiences with Dolby Vision IQ standard and surround sound from Dolby Atmos Powerful gaming experience with HDMI 2.1, VRR, HFR and a unique game menu Low without flickers, reduces eye fatigue and allows safe viewing",
    },
    {
      seller: ObjectId("60e87e474f88c268a82a9ed3"),
      name: "SAMSUNG 75 LED SMART 4K",
      category: "TV",
      image: ["/seller2/samsung75.png"],
      price: 750,
      countInStock: 32,
      brand: "SAMSUNG",
      rating: 0,
      numReviews: 0,
      description: "LED 4K SMART",
    },
    {
      seller: ObjectId("60e87e474f88c268a82a9ed3"),
      name: "SAMSUNG 65 LED SMART 4K",
      category: "TV",
      image: ["/seller2/sam.png"],
      price: 650,
      countInStock: 32,
      brand: "SAMSUNG",
      rating: 0,
      numReviews: 0,
      description: "LED 4K SMART",
    },
    {
      seller: ObjectId("60e87e474f88c268a82a9ed3"),
      name: "FUJICOM refrigerator 324 liter FJ-NF383XR",
      category: "refrigerator",
      image: ["/seller2/frigder1.png", "/seller2/frigder2.png"],
      price: 1000,
      countInStock: 10,
      brand: "FUJICOM",
      rating: 0,
      numReviews: 0,
      description: "Overall volume: 324 liters (net)",
    },
    {
      seller: ObjectId("60e87e474f88c268a82a9ed3"),
      name: "FUJICOM refrigerator 230 liter FJ-NF2761M",
      category: "refrigerator",
      image: ["/seller2/frigder3.png", "/seller2/frigder4.png"],
      price: 870,
      countInStock: 37,
      brand: "FUJICOM",
      rating: 0,
      numReviews: 0,
      description:
        "Integral refrigerator for construction in kitchen cabinets for a clean and perfect design Lighting that illuminates the surface of the refrigerator in strong light, which makes finding the products complete inside the refrigerator Total volume: 230 liters net",
    },
    {
      seller: ObjectId("60e87e474f88c268a82a9ed3"),
      name: "LG refrigerator 714 liter GM859RWC",
      category: "refrigerator",
      image: [
        "/seller2/frigder5.jpg",
        "/seller2/frigder6.jpg",
        "/seller2/frigder7.jpg",
      ],
      price: 1300,
      countInStock: 37,
      brand: "LG",
      rating: 0,
      numReviews: 0,
      description:
        "Integral refrigerator for construction in kitchen cabinets for a clean and perfect design Lighting that illuminates the surface of the refrigerator in strong light, which makes finding the products complete inside the refrigerator Total volume: 230 liters net",
    },
    {
      seller: ObjectId("60e87e474f88c268a82a9ed3"),
      name: "XIAOMI Redmi Note 10S",
      category: "phones",
      image: ["/seller2/phone1.png"],
      price: 330,
      countInStock: 100,
      brand: "XIAOMI",
      rating: 0,
      numReviews: 0,
      description: "redmi note best phone",
    },
  ],
};
export default data;
